### ISSUE TITLE
missing declaration

### ISSUE THREAD

**Issue by phesterman** [rlisle/Patriot#24]
Ron,  
I was very happy to find this project and really appreciate all the work you've put into it.  Just thought I'd let you know: when I compiled the PatriotLight example I encountered several errors apparently generated because _brightness is not declared in PatriotLight.h. 
Peter

**Comment by rlisle** [comment]
Hi Peter,
Sorry to hear you're having trouble compiling the code. I've been working on adding brightness controls in a git branch called "brightness", and maybe accidentally got the master branch code out of synch.  I'll try to finish up those changes and merge to master over the next couple weeks.

**Comment by phesterman** [comment]
Thanks, Ron!  Happy New Year!

**Comment by TtimmEwath** [comment]
Hey Ron,
Any update on this? I love what you've been doing and I've been working on updating some of my devices with the newer functionality you've been adding. I'm excited to try it out!

**Comment by rlisle** [comment]
Sorry about that. I'm having trouble remembering how I setup the #includes, and searching through all the READMEs I wrote I don't see any clear instructions on how to build the code from scratch. It's evolved over many years, and I can see why it'd be a struggle for somebody just trying to download and build it. Are you using the web IDE or trying to build from the command line?

**Comment by TtimmEwath** [comment]
Thanks for the quick response! I'm using the photon web IDE. My old project was using the photon to turn a servo after using a voice command on an echo device. I made it work by tying the servo position to the on-board LED status of on or off. Also I've recently added a new photon but I'm not sure how to get my echo devices to "discover" it. I don't recall having that issue before.

**Comment by rlisle** [comment]
I've published IoT library version 3.1. Please try your code with the new version and see if that fixes everything for you. Thank you for your patience.
